AdaFruit Logging is required
```python
Adafruit CircuitPython 5.0.0-beta.0-2634-gda61845f5-dirty on 2020-08-24; FeatherS2 with ESP32S2
>>> import os
>>> os.listdir('/lib')
['adafruit_requests.mpy', 'adafruit_azureiot', '._adafruit_azureiot', 'adafruit_minimqtt', '._adafruit_minimqtt', 'adafruit_binascii.mpy', '._adafruit_binascii.mpy', 'adafruit_ntp.mpy', '._adafruit_ntp.mpy']
>>> import adafruit_minimqtt.adafruit_minimqtt as MINIQTT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_minimqtt/adafruit_minimqtt.py", line 47, in <module>
ImportError: no module named 'adafruit_logging'

```